CREATE SEQUENCE CUSTOMERS_ID_SEQ;

CREATE TABLE CUSTOMERS (
    ID SERIAL NOT NULL,
    CODE INTEGER NOT NULL,
    FULL_NAME VARCHAR NOT NULL,
    CUSTOMER_PASSWORD VARCHAR NOT NULL,
    CITY VARCHAR NOT NULL,
    COUNTRY VARCHAR NOT NULL,
    AGE INTEGER NOT NULL DEFAULT 0,
    SALARY INTEGER NOT NULL DEFAULT 0,
    PHONE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (CODE, COUNTRY)
);

ALTER SEQUENCE CUSTOMERS_ID_SEQ OWNED BY CUSTOMERS.ID;
