CREATE SEQUENCE CUSTOMERS_ID_SEQ;

CREATE TABLE CUSTOMERS (
    ID SERIAL NOT NULL,
    CODE INTEGER NOT NULL,
    FULL_NAME VARCHAR NOT NULL,
    CUSTOMER_PASSWORD VARCHAR NOT NULL,
    AGE INTEGER,
    SALARY DECIMAL,
    PHONE INTEGER,
    PRIMARY KEY (ID)
);

ALTER SEQUENCE CUSTOMERS_ID_SEQ OWNED BY CUSTOMERS.ID;