CREATE SEQUENCE CUSTOMERS_ID_SEQ;

CREATE TABLE CUSTOMERS (
    ID SERIAL NOT NULL,
    CODE BIGINT NOT NULL,
    FULL_NAME VARCHAR NOT NULL,
    CUSTOMER_PASSWORD VARCHAR NOT NULL,
    CITY VARCHAR NOT NULL,
    COUNTRY VARCHAR NOT NULL,
    AGE INTEGER NOT NULL DEFAULT 0,
    SALARY BIGINT NOT NULL DEFAULT 0,
    PHONE BIGINT NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (CODE, COUNTRY),
    UNIQUE (PHONE)
);

ALTER SEQUENCE CUSTOMERS_ID_SEQ OWNED BY CUSTOMERS.ID;
