CREATE SEQUENCE VS_SERVICES_ID_SEQ;

CREATE TABLE VS_SERVICES (
    ID SERIAL NOT NULL,
    CUSTOMER INTEGER NOT NULL REFERENCES CUSTOMERS(ID),
	SERVICE INTEGER NOT NULL REFERENCES SERVICES(ID),
    PRIMARY KEY (ID),
    UNIQUE (CUSTOMER, SERVICE)
);

ALTER SEQUENCE VS_SERVICES_ID_SEQ OWNED BY VS_SERVICES.ID;
